swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /results:
    get:
      operationId: "results.read"
      tags:
        - "Results"
      summary: "The results of the Daily Poll"
      description: "Read the results of the current Daily Poll"
      responses:
        200:
          description: "Successful read results list operation"
          schema:
            type: "array"
            items:
              properties:
                name:
                  type: "string"
                count:
                  type: "string"
                timestamp:
                  type: "string"